### ISSUE TITLE
Variant grid error

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#10]
Going to

    http://localhost/marello/marello/product/view/2?_enableContentProviders=mainMenu

causes

    An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 47 near 'stock) AS stockLevel': Error: Class Marello\Bundle\InventoryBundle\Entity\StockLevel has no field or association named stock") in vendor/marellocommerce/marello/src/Marello/Bundle/ProductBundle/Resources/views/Variant/widget/info.html.twig at line 8.

changing all occurrences of

    - SUM(l.stock) AS stockLevel

to

    - COALESCE(SUM(l.inventory), 0) AS stockLevel

in file

    Marello/Bundle/ProductBundle/Resources/config/datagrid.yml

solves that error

**Comment by 24198** [comment]
Hi @clicktrend,

Thanks for reporting! We will fix this as soon as possible and will be available shortly and in the upcoming release.


Kind Regards,


Jaimy Casteleijn
