### ISSUE TITLE
Purchase order grid error

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#11]
Error like #10 .

Replace alle 3 occurrences of

    "l.stock - l.allocatedStock"

with

    "l.inventory - l.allocatedInventory"

in file

    Marello/Bundle/PurchaseOrderBundle/Resources/config/datagrid.yml

**Comment by 24198** [comment]
Hi @clicktrend,

Thanks for noticing! We've fixed this in the upcoming release!

Kind Regards,

Jaimy Casteleijn
