### ISSUE TITLE
Rest serialize error

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#14]
Field "inventory" of rest call

    /api/rest/latest/products

is "null". Removing "result_name" hydrates entity correctly in [ProductApiEntityManager](https://github.com/marellocommerce/marello/blob/master/src/Marello/Bundle/ProductBundle/Entity/Manager/ProductApiEntityManager.php#L57).

**Comment by 24198** [comment]
Hi @clicktrend,

Thanks for noticing! We've fixed this in the upcoming release!

Kind Regards,

Jaimy Casteleijn
