### ISSUE TITLE
Datagrid sorter column error

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#16]
Hi,

after [line 158](https://github.com/marellocommerce/marello/blob/master/src/Marello/Bundle/ProductBundle/Resources/config/oro/datagrids.yml#L158) add stockLevel column

    stockLevel:     { data_name: stockLevel }

**Comment by 24198** [comment]
Hi @clicktrend 

Thank you for reporting, this has been fixed in the GA release!

Kind Regards,


Jaimy
