### ISSUE TITLE
Quantity set to 0 on OrderItem line in order

### ISSUE THREAD

**Issue by brainOut** [marellocommerce/marello#51]
On 1.5.1 release, if i create an order and set the quantity to 0 for an orderItem, the orderItem line is not in error, but the 0 value is accepted as a good value.

![image](https://user-images.githubusercontent.com/17732411/51039455-a6032a80-15b5-11e9-9dc6-d607fac5b412.png)

The order can be processed as a "normal" one, and stock movements can be visible too.

![image](https://user-images.githubusercontent.com/17732411/51039576-cd59f780-15b5-11e9-826b-457dde1c9899.png)

**Comment by 24198** [comment]
Hi @brainOut,

The issue has been resolved in patch version 1.5.2. In this version, additional validation has been added specifically for this case where you are now not longer able to create an Order with OrderLineItems that have 0 as quantity.

Thanks for reporting!


Kind Regards,


Jaimy Casteleijn
