### ISSUE TITLE
Localized mail aren't sent: Function does not exist anymore

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#61]
https://github.com/marellocommerce/marello/blob/1999cc10e65e8f726b9b8d4ea5a2ba57c2fe7061/src/Marello/Bundle/LocaleBundle/Manager/EmailTemplateManager.php#L78

Use Oro\Bundle\EmailBundle\Provider\EmailTemplateContentProvider::getTemplateContent(EmailTemplateCriteria $criteria, Localization $localization, array $templateParams) instead

**Comment by 24198** [comment]
Hi @clicktrend,

Can you please verify the versions of Marello and Oro Platform (Marello 3.0 should be running Platform 4.1.0 or higher), as this function does exist in  [Oro Platform 4.1.x](https://github.com/oroinc/platform/blob/4.1.0/src/Oro/Bundle/EmailBundle/Entity/Repository/EmailTemplateRepository.php#L146). We have changed this as the previous function we used was removed from the Platform.

Kind Regards,

Jaimy

**Comment by clicktrend** [comment]
I'm using Marello 3.0 and function "findWithLocalizations" still exists but without the second parameter!

**Comment by 24198** [comment]
Hi @clicktrend,

Thanks for the fast response, we are investigating the issue and have marked it as a bug for now. We will include a fix in the next release. Thanks for reporting!

Kind Regards,

Jaimy

**Comment by 24198** [comment]
Hi @clicktrend,

The issue has been fixed in the [3.0.1 release](https://github.com/marellocommerce/marello/tree/3.0.1). This will allow you to use the localization for notifications as intented.

Kind Regards,

Jaimy
