### ISSUE TITLE
ForbiddenException class doesn't exists

### ISSUE THREAD

**Issue by Peekmo** [marellocommerce/marello#65]
Hello,

It seems that in Marello 3.0.1, in `Marello\Bundle\ReturnBundle\Controller\ReturnController` if you try to create a return from a non shipped order, you throw a `Oro\Bundle\SecurityBundle\Exception\ForbiddenException`, but it seems that this class doesn't exists.

**Comment by 24198** [comment]
Hi @Peekmo,

Thank you for reporting, we have implemented a fix by using the preferential exception instead of the removed class. The fix can be found in https://github.com/marellocommerce/marello/tree/3.0.8.

Thanks again,

Jaimy
