### ISSUE TITLE
PHP compliance ?

### ISSUE THREAD

**Issue by touchweb-vincent** [marellocommerce/marello#69]
Hello,

It would be appreciated if you could provide inside your composer.json the version PHP supported.

Thanks you,

Vincent

**Comment by 24198** [comment]
Hi @touchweb-vincent,

PHP version(s) support dependency is provided in [oro/platform](https://github.com/marellocommerce/marello-application/blob/3.1.0/composer.lock#L5671) dependency. We rely on that dependency for supported PHP versions too.

Hope this helps,

Jaimy

**Comment by touchweb-vincent** [comment]
Hello Jaimy,

Sounds good, thanks you for the quick reply :)

Vincent
