### ISSUE TITLE
Where is the marello api doc?

### ISSUE THREAD

**Issue by benyang2015** [marellocommerce/marello#9]

**Comment by 24198** [comment]
Hi @benyang2015,

By default the api docs you're looking for are in the application itself. These docs include which api endpoints are available for 3rd party developers. You can find the docs when you get to navigate to marello.example.com/api/doc in your application. Hope this helps!

Kind Regards,

Jaimy Casteleijn

**Comment by benyang2015** [comment]
Can't get the order!
<img width="1209" alt="marello-get-order-api" src="https://cloud.githubusercontent.com/assets/15188607/20388973/45af21d4-ad02-11e6-8e3b-7b955fc0846c.png">

**Comment by 24198** [comment]
Hi @benyang2015,

There is some great documentation on how to use the Sandbox in the Oro Application, [The Oro book - Api Sandbox](https://www.orocrm.com/documentation/index/current/book/data-api#how-to-use-the-sandbox), this will help you setup the sandbox. Some smaller things like, generating a API-key for your current user, setting the Authentication option to WSSE at the top of the page (marello.example.com/api/doc page that is) are some of the most commonly forgotten settings before using the sandbox. Generating an API key can be done on the user view (marello.example.com/user/view/{id}) by pressing the 'generate key' button. 

Hopefully the article and explanation helps!

Kind Regards,

Jaimy Casteleijn

**Comment by 24198** [comment]
Closing the issue since no responds has been given by the original reporter on whether his question is actually being answered.
